var color_dictionary = {
	"Afghanistan": "#eeeeee",
	"Angola": "#eeeeee",
	"Albania": "#eeeeee",
	"United Arab Emirates": "#eeeeee",
	"Argentina": "#eeeeee",
	"Armenia": "#eeeeee",
	"Antarctica": "#eeeeee",
	"French Southern and Antarctic Lands": "#eeeeee",
	"Australia": "#eeeeee",
	"Austria": "#eeeeee",
	"Azerbaijan": "#eeeeee",
	"Burundi": "#eeeeee",
	"Belgium": "#eeeeee",
	"Benin": "#eeeeee",
	"Burkina Faso": "#eeeeee",
	"Bangladesh": "#eeeeee",
	"Bulgaria": "#eeeeee",
	"The Bahamas": "#eeeeee",
	"Bosnia and Herzegovina": "#eeeeee",
	"Belarus": "#eeeeee",
	"Belize": "#eeeeee",
	"Bolivia": "#eeeeee",
	"Brazil": "#eeeeee",
	"Brunei": "#eeeeee",
	"Bhutan": "#eeeeee",
	"Botswana": "#eeeeee",
	"Central African Republic": "#eeeeee",
	"Canada": "#eeeeee",
	"Switzerland": "#eeeeee",
	"Chile": "#eeeeee",
	"China": "#eeeeee",
	"Ivory Coast": "#eeeeee",
	"Cameroon": "#eeeeee",
	"Democratic Republic of the Congo": "#eeeeee",
	"Republic of the Congo": "#eeeeee",
	"Colombia": "#eeeeee",
	"Costa Rica": "#eeeeee",
	"Cuba": "#eeeeee",
	"Cyprus": "#eeeeee",
	"Czech Republic": "#eeeeee",
	"Germany": "#eeeeee",
	"Djibouti": "#eeeeee",
	"Denmark": "#eeeeee",
	"Dominican Republic": "#eeeeee",
	"Algeria": "#eeeeee",
	"Ecuador": "#eeeeee",
	"Egypt": "#eeeeee",
	"Eritrea": "#eeeeee",
	"Spain": "#eeeeee",
	"Estonia": "#eeeeee",
	"Ethiopia": "#eeeeee",
	"Finland": "#eeeeee",
	"Fiji": "#eeeeee",
	"Falkland Islands": "#eeeeee",
	"France": "#eeeeee",
	"Gabon": "#eeeeee",
	"United Kingdom": "#eeeeee",
	"England": "#eeeeee",
	"Scotland": "#eeeeee",
	"Georgia": "#eeeeee",
	"Ghana": "#eeeeee",
	"Guinea": "#eeeeee",
	"Gambia": "#eeeeee",
	"Guinea Bissau": "#eeeeee",
	"Equatorial Guinea": "#eeeeee",
	"Greece": "#eeeeee",
	"Greenland": "#eeeeee",
	"Guatemala": "#eeeeee",
	"Guyana": "#eeeeee",
	"Honduras": "#eeeeee",
	"Croatia": "#eeeeee",
	"Haiti": "#eeeeee",
	"Hungary": "#eeeeee",
	"Indonesia": "#eeeeee",
	"India": "#eeeeee",
	"Ireland": "#eeeeee",
	"Iran": "#eeeeee",
	"Iraq": "#eeeeee",
	"Iceland": "#eeeeee",
	"Israel": "#eeeeee",
	"Italy": "#eeeeee",
	"Jamaica": "#eeeeee",
	"Jordan": "#eeeeee",
	"Japan": "#eeeeee",
	"Kazakhstan": "#eeeeee",
	"Kenya": "#eeeeee",
	"Kyrgyzstan": "#eeeeee",
	"Cambodia": "#eeeeee",
	"South Korea": "#eeeeee",
	"Kuwait": "#eeeeee",
	"Laos": "#eeeeee",
	"Lebanon": "#eeeeee",
	"Liberia": "#eeeeee",
	"Libya": "#eeeeee",
	"Sri Lanka": "#eeeeee",
	"Lesotho": "#eeeeee",
	"Lithuania": "#eeeeee",
	"Luxembourg": "#eeeeee",
	"Latvia": "#eeeeee",
	"Morocco": "#eeeeee",
	"Moldova": "#eeeeee",
	"Madagascar": "#eeeeee",
	"Mexico": "#eeeeee",
	"Macedonia": "#eeeeee",
	"Mali": "#eeeeee",
	"Myanmar": "#eeeeee",
	"Montenegro": "#eeeeee",
	"Mongolia": "#eeeeee",
	"Mozambique": "#eeeeee",
	"Mauritania": "#eeeeee",
	"Malawi": "#eeeeee",
	"Malaysia": "#eeeeee",
	"Namibia": "#eeeeee",
	"New Caledonia": "#eeeeee",
	"Niger": "#eeeeee",
	"Nigeria": "#eeeeee",
	"Nicaragua": "#eeeeee",
	"Netherlands": "#eeeeee",
	"Norway": "#eeeeee",
	"Nepal": "#eeeeee",
	"New Zealand": "#eeeeee",
	"Oman": "#eeeeee",
	"Pakistan": "#eeeeee",
	"Panama": "#eeeeee",
	"Peru": "#eeeeee",
	"Philippines": "#eeeeee",
	"Papua New Guinea": "#eeeeee",
	"Poland": "#eeeeee",
	"Puerto Rico": "#eeeeee",
	"North Korea": "#eeeeee",
	"Portugal": "#eeeeee",
	"Paraguay": "#eeeeee",
	"Qatar": "#eeeeee",
	"Romania": "#eeeeee",
	"Russia": "#eeeeee",
	"Rwanda": "#eeeeee",
	"Saudi Arabia": "#eeeeee",
	"Sudan": "#eeeeee",
	"South Sudan": "#eeeeee",
	"Senegal": "#eeeeee",
	"Solomon Islands": "#eeeeee",
	"Sierra Leone": "#eeeeee",
	"El Salvador": "#eeeeee",
	"Somalia": "#eeeeee",
	"Republic of Serbia": "#eeeeee",
	"Suriname": "#eeeeee",
	"Slovakia": "#eeeeee",
	"Slovenia": "#eeeeee",
	"Sweden": "#eeeeee",
	"Swaziland": "#eeeeee",
	"Syria": "#eeeeee",
	"Chad": "#eeeeee",
	"Togo": "#eeeeee",
	"Thailand": "#eeeeee",
	"Tajikistan": "#eeeeee",
	"Turkmenistan": "#eeeeee",
	"East Timor": "#eeeeee",
	"Trinidad and Tobago": "#eeeeee",
	"Tunisia": "#eeeeee",
	"Turkey": "#eeeeee",
	"Taiwan": "#eeeeee",
	"United Republic of Tanzania": "#eeeeee",
	"Uganda": "#eeeeee",
	"Ukraine": "#eeeeee",
	"Uruguay": "#eeeeee",
	"United States of America": "#eeeeee",
	"Uzbekistan": "#eeeeee",
	"Venezuela": "#eeeeee",
	"Vietnam": "#eeeeee",
	"Vanuatu": "#eeeeee",
	"West Bank": "#eeeeee",
	"Yemen": "#eeeeee",
	"South Africa": "#eeeeee",
	"Zambia": "#eeeeee",
	"Zimbabwe": "#eeeeee",
};

var code_dictionary = {
	"Afghanistan": "AFG",
	"Angola": "AGO",
	"Albania": "ALB",
	"United Arab Emirates": "ARE",
	"Argentina": "ARG",
	"Armenia": "ARM",
	"Antarctica": "ATA",
	"French Southern and Antarctic Lands": "ATF",
	"Australia": "AUS",
	"Austria": "AUT",
	"Azerbaijan": "AZE",
	"Burundi": "BDI",
	"Belgium": "BEL",
	"Benin": "BEN",
	"Burkina Faso": "BFA",
	"Bangladesh": "BGD",
	"Bulgaria": "BGR",
	"The Bahamas": "BHS",
	"Bosnia and Herzegovina": "BIH",
	"Belarus": "BLR",
	"Belize": "BLZ",
	"Bolivia": "BOL",
	"Brazil": "BRA",
	"Brunei": "BRN",
	"Bhutan": "BTN",
	"Botswana": "BWA",
	"Central African Republic": "CAF",
	"Canada": "CAN",
	"Switzerland": "CHE",
	"Chile": "CHL",
	"China": "CHN",
	"Ivory Coast": "CIV",
	"Cameroon": "CMR",
	"Democratic Republic of the Congo": "COD",
	"Republic of the Congo": "COG",
	"Colombia": "COL",
	"Costa Rica": "CRI",
	"Cuba": "CUB",
	"Cyprus": "CYP",
	"Czech Republic": "CZE",
	"Germany": "DEU",
	"Djibouti": "DJI",
	"Denmark": "DNK",
	"Dominican Republic": "DOM",
	"Algeria": "DZA",
	"Ecuador": "ECU",
	"Egypt": "EGY",
	"Eritrea": "ERI",
	"Spain": "ESP",
	"Estonia": "EST",
	"Ethiopia": "ETH",
	"Finland": "FIN",
	"Fiji": "FJI",
	"Falkland Islands": "FLK",
	"France": "FRA",
	"Gabon": "GAB",
	"United Kingdom": "GBR",
	"England": "GBR",
	"Scotland": "GBR",
	"Georgia": "GEO",
	"Ghana": "GHA",
	"Guinea": "GIN",
	"Gambia": "GMB",
	"Guinea Bissau": "GNB",
	"Equatorial Guinea": "GNQ",
	"Greece": "GRC",
	"Greenland": "GRL",
	"Guatemala": "GTM",
	"Guyana": "GUY",
	"Honduras": "HND",
	"Croatia": "HRV",
	"Haiti": "HTI",
	"Hungary": "HUN",
	"Indonesia": "IDN",
	"India": "IND",
	"Ireland": "IRL",
	"Iran": "IRN",
	"Iraq": "IRQ",
	"Iceland": "ISL",
	"Israel": "ISR",
	"Italy": "ITA",
	"Jamaica": "JAM",
	"Jordan": "JOR",
	"Japan": "JPN",
	"Kazakhstan": "KAZ",
	"Kenya": "KEN",
	"Kyrgyzstan": "KGZ",
	"Cambodia": "KHM",
	"South Korea": "KOR",
	"Kuwait": "KWT",
	"Laos": "LAO",
	"Lebanon": "LBN",
	"Liberia": "LBR",
	"Libya": "LBY",
	"Sri Lanka": "LKA",
	"Lesotho": "LSO",
	"Lithuania": "LTU",
	"Luxembourg": "LUX",
	"Latvia": "LVA",
	"Morocco": "MAR",
	"Moldova": "MDA",
	"Madagascar": "MDG",
	"Mexico": "MEX",
	"Macedonia": "MKD",
	"Mali": "MLI",
	"Myanmar": "MMR",
	"Montenegro": "MNE",
	"Mongolia": "MNG",
	"Mozambique": "MOZ",
	"Mauritania": "MRT",
	"Malawi": "MWI",
	"Malaysia": "MYS",
	"Namibia": "NAM",
	"New Caledonia": "NCL",
	"Niger": "NER",
	"Nigeria": "NGA",
	"Nicaragua": "NIC",
	"Netherlands": "NLD",
	"Norway": "NOR",
	"Nepal": "NPL",
	"New Zealand": "NZL",
	"Oman": "OMN",
	"Pakistan": "PAK",
	"Panama": "PAN",
	"Peru": "PER",
	"Philippines": "PHL",
	"Papua New Guinea": "PNG",
	"Poland": "POL",
	"Puerto Rico": "PRI",
	"North Korea": "PRK",
	"Portugal": "PRT",
	"Paraguay": "PRY",
	"Qatar": "QAT",
	"Romania": "ROU",
	"Russia": "RUS",
	"Rwanda": "RWA",
	"Saudi Arabia": "SAU",
	"Sudan": "SDN",
	"South Sudan": "SDS",
	"Senegal": "SEN",
	"Solomon Islands": "SLB",
	"Sierra Leone": "SLE",
	"El Salvador": "SLV",
	"Somalia": "SOM",
	"Republic of Serbia": "SRB",
	"Suriname": "SUR",
	"Slovakia": "SVK",
	"Slovenia": "SVN",
	"Sweden": "SWE",
	"Swaziland": "SWZ",
	"Syria": "SYR",
	"Chad": "TCD",
	"Togo": "TGO",
	"Thailand": "THA",
	"Tajikistan": "TJK",
	"Turkmenistan": "TKM",
	"East Timor": "TLS",
	"Trinidad and Tobago": "TTO",
	"Tunisia": "TUN",
	"Turkey": "TUR",
	"Taiwan": "TWN",
	"United Republic of Tanzania": "TZA",
	"Uganda": "UGA",
	"Ukraine": "UKR",
	"Uruguay": "URY",
	"United States of America": "USA",
	"Uzbekistan": "UZB",
	"Venezuela": "VEN",
	"Vietnam": "VNM",
	"Vanuatu": "VUT",
	"West Bank": "PSE",
	"Yemen": "YEM",
	"South Africa": "ZAF",
	"Zambia": "ZMB",
	"Zimbabwe": "ZWE",
};